export const medicalHealthTips: string[] = [
  "Stay hydrated by drinking at least 6–8 glasses of water daily.",
  "Maintain a balanced diet rich in fruits, vegetables, and whole grains.",
  "Get at least 7–8 hours of sleep daily to support your immune system.",
  "Wash your hands frequently to reduce the spread of infections.",
  "Avoid smoking and limit alcohol consumption to protect long-term health.",
  "Take short breaks every hour if you sit for long periods.",
  "Engage in at least 30 minutes of moderate physical activity every day.",
  "Keep your vaccinations up to date as recommended by health professionals.",
  "Monitor your blood pressure regularly if you have a family history of hypertension.",
  "Practice mindful breathing to reduce stress and improve mental health.",
  "Limit sugar and processed foods to lower the risk of chronic diseases.",
  "Consume lean protein sources such as legumes, fish, and nuts.",
  "Wear sunscreen daily to protect against harmful UV radiation.",
  "Avoid excessive salt intake to reduce the risk of heart disease.",
  "Schedule regular health check-ups for early detection of illnesses.",
  "Maintain good posture to prevent back and neck pain.",
  "Ensure adequate calcium intake for strong bones and teeth.",
  "Take short walks after meals to improve digestion and blood sugar control.",
  "Avoid sleeping immediately after eating to prevent acidity and discomfort.",
  "Practice proper oral hygiene by brushing and flossing daily.",
  "Manage stress through meditation, yoga, or light exercise.",
  "Limit screen time before bed to improve sleep quality.",
  "Include omega-3–rich foods like walnuts and flax seeds in your diet.",
  "Stay physically active to maintain a healthy weight and metabolism.",
  "Replace sugary beverages with water, herbal tea, or infused water.",
  "Perform regular stretching to maintain flexibility and reduce stiffness.",
  "Keep your surroundings clean to prevent infections and allergies.",
  "Eat smaller, more frequent meals to maintain stable energy levels.",
  "Avoid self-medication; consult a doctor when symptoms persist.",
  "Maintain a healthy routine to support your mental and physical well-being.",
];
